#!/bin/sh
# --> /etc/initramfs-tools/hooks/usb-keyfile

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions


copy_file usb-keyfile.conf /etc/usb-keyfile.conf

# 1. 包含必要的内核模块
manual_add_modules usb-storage uas sd_mod
manual_add_modules vfat ext4  # 根据你的 USB 文件系统选择

# 2. 复制必要命令
copy_exec /sbin/blkid /sbin/blkid
copy_exec /bin/mount /bin/mount
copy_exec /bin/umount /bin/umount
copy_exec /bin/cat /bin/cat
copy_exec /bin/sleep /bin/sleep
copy_exec /sbin/fsck.vfat /sbin/fsck.vfat
copy_exec /sbin/fsck.ext4 /sbin/fsck.ext4
copy_exec /usr/bin/systemd-cryptsetup /bin/systemd-cryptsetup
copy_exec /usr/bin/systemd-ask-password /bin/sytemd-ask-password

# 复制依赖库（通常 busybox 已包含，但保险起见）
#for bin in /sbin/blkid /bin/mount; do
#    for lib in $(ldd "$bin" 2>/dev/null | awk '/=>/ && !/not found/ {print $3}'); do
#        [ -e "$lib" ] && copy_exec "$lib"
#    done
#done

