#!/bin/sh
# --> /etc/initramfs-tools/scripts/local-top/usb-keyfile-unlock

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions

CONF="/etc/usb-keyfile.conf"

if [ -r "$CONF" ];then
    . "$CONF"
else
    log_warning_msg "$CONF not configure, exit"
    log_end_msg
    exit 1
fi

if [ -z "$USB_UUID" ] || [ -z "$KEYFILE_PATH" ] || [ -z "$LUKS_CONF" ];then
    log_warning_msg "USB_UUID KEYFILE_PATH LUKS_CONF, require configure."
    log_end_msg
    exit 1
fi

if [ ! -r "$LUKS_CONF" ];then
    log_warning_msg "LUKS_CONF: $LUKS_CONF not found."
    log_end_msg
    exit 1
fi

TMP_UNLOCK="/run/usb-keyfile-unlock.lock"
TMP_UNLOCK_OK="/run/usb-keyfile-unlock.lock-ok"

trap "rm $TMP_UNLOCK $TMP_UNLOCK_OK" EXIT


luks_unlock(){

    (
        exec 20>"$TMP_UNLOCK"
        flock 20

        if [ -f "$TMP_UNLOCK_OK" ];then
            _log_msg "Detected already unlocked, exit current operation."
            log_end_msg
            return 0
        fi


        local keyfile="$1"
        local luksuuid luksname luks_dev
        _log_msg "Keyfile found, attempting unlock..."
        log_end_msg
        while read luksuuid luksname;
        do
            # 跳过空行和注释行
            [ -z "$luksuuid" ] && continue
            case "$luksuuid" in \#*)
                continue
                ;;
            esac

            luks_dev=$(blkid -t "UUID=$luksuuid" -o device 2>/dev/null)
            if [ -z "$luks_dev" ];then
                log_warning_msg "not found LUKS UUID: $luksuuid"
                log_end_msg
                continue
            fi

            if cryptsetup -d "${keyfile}" open "$luks_dev" "$luksname";then
                :>"$TMP_UNLOCK_OK"
                log_success_msg "LUKS $luksname unlock done."
                log_end_msg
            else
                log_warning_msg "Failed to unlock LUKS $luksname"
                log_end_msg
                return 1
            fi

        done < "$LUKS_CONF"

        return 0
    )
}


usb_key(){
    
    local recode
    local RUN_USB="/run/usb"
    # udevadm wait -t 10 "/dev/disk/by-uuid/$USB_UUID"
    udevadm wait "/dev/disk/by-uuid/$USB_UUID"
    # 使用 blkid 查找设备
    USB_DEV=$(blkid -t "UUID=$USB_UUID" -o device 2>/dev/null)

    if [ -n "$USB_DEV" ]; then
        _log_msg "USB device found: USB_KEY"
        log_end_msg

        mkdir -p $RUN_USB

        if mount -o ro "$USB_DEV" $RUN_USB; then
            _log_msg "USB mounted successfully"
            log_end_msg
    
            KEYFILE="${RUN_USB}$KEYFILE_PATH"
            if [ -r "$KEYFILE" ]; then
                if luks_unlock "$KEYFILE";then
                    log_success_msg "LUKS unlocked via USB keyfile."
                    log_end_msg
                    recode=0
                else
                    log_warning_msg "Keyfile: $KEYFILE found but unlock Failed"
                    log_end_msg
                    recode=1
                fi
            else
                log_warning_msg "Keyfile not found: $KEYFILE"
                log_end_msg
                recode=1
            fi
            umount $RUN_USB
        else
            log_warning_msg "Failed to mount USB device"
            log_end_msg
            recode=1
        fi

        rmdir $RUN_USB

    else
        log_warning_msg "USB device with USB_KEY not found"
        log_end_msg
        recode=1
    fi

    return $recode
}


usb(){
    for _ in $(seq 30)
    do
        if usb_key; then
            break
        fi
    done
}


user_input(){
    # === 交互式密码输入 ===
    for _ in $(seq 30)
    do
        _log_msg "Please enter the password to decrypt LUKS:"

        stty -echo
        # read -t 3 pw
        read pw
        stty echo

        if [ -n "$pw" ]; then
            printf "$pw" > /run/luks-pwfile
            if luks_unlock "/run/luks-pwfile";then
                rm -f /run/luks-pwfile
                return 0
            else
                _log_msg "Password unlock failed, retry..."
                log_end_msg
                rm -f /run/luks-pwfile
            fi
        fi
    done
}

usb &
pid_usb=$!

user_input

wait $pid_usb

exit 0
