#!/bin/sh
# --> /etc/initramfs-tools/scripts/local-top/usb-keyfile-unlock

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /scripts/functions

CONF="/etc/usb-keyfile.conf"

if [ -r "$CONF" ];then
    . "$CONF"
else
    log_warning_msg "$CONF not configure, exit"
    exit 1
fi

if [ -z "$USB_UUID" ] || [ -z "$KEYFILE_PATH" ] || [ -z "$NAME_LUKS" ] || [ -z "$LUKS_UUID" ];then
    log_warning_msg "USB_UUID KEYFILE_PATH NAME_LUKS LUKS_UUID, require configure."
    exit 1
fi



LUKS_DEVS=()
for LUKS_UUID in "${LUKS_UUIDS[@]}";
do
    log_info_msg "Checking for LUKS (UUID=$LUKS_UUID)..."
    LUKS_DEV=$(blkid -t "UUID=$LUKS_UUID" -o device 2>/dev/null)
    if [ -z "$LUKS_DEV" ];then
        log_warning_msg "not found LUKS UUID: $LUKS_UUID"
    fi
    LUKS_DEVS+=("$LUKS_DEV")
done


LUKS_DEV=$(blkid -t "UUID=$LUKS_UUID" -o device 2>/dev/null)
if [ -z "$LUKS_DEV" ];then
    log_warning_msg "not found LUKS UUID: $LUKS_UUID"
    exit 1
fi


usb_unlock(){
    
    local RUN_USB="/run/usb"
    udevadm wait -t 10 "/dev/disk/by-uuid/$USB_UUID"
    # 使用 blkid 查找设备
    USB_DEV=$(blkid -t "UUID=$USB_UUID" -o device 2>/dev/null)

    if [ -n "$USB_DEV" ]; then
        _log_msg "USB device found: USB_KEY"

        mkdir -p $RUN_USB

        if mount "$USB_DEV" $RUN_USB; then
            _log_msg "USB mounted successfully"
    
            KEYFILE="${RUN_USB}$KEYFILE_PATH"
            if [ -r "$KEYFILE" ]; then
                _log_msg "Keyfile found, attempting unlock..."
                cryptsetup open -d "${RUN_USB}${KEYFILE_PATH}" "$LUKS_DEV" "$NAME_LUKS"
                _log_msg "LUKS Root unlock done."
                umount $RUN_USB
                rmdir $RUN_USB
                return 0
            else
                log_warning_msg "Keyfile not found: $KEYFILE"
                return 1
            fi
            umount $RUN_USB
        else
            log_warning_msg "Failed to mount USB device"
            return 1
        fi
    else
        log_warning_msg "USB device with USB_KEY not found"
        return 1
    fi
}

if usb_unlock; then
    log_success_msg "LUKS unlocked via USB keyfile."
    exit 0
else
    # === 回退到交互式密码输入 ===
    _log_msg "Please enter the password to decrypt LUKS $LUKS_UUID:"
    cryptsetup open "$LUKS_DEV" "$NAME_LUKS"
    if [ $? -ne 0 ]; then
        log_warning_msg "Failed to unlock LUKS without USB keyfile"
        exit 1
    fi
    _log_msg "LUKS Root unlock done without USB keyfile."
    exit 0
fi 
